[window]

option_as_alt = "Both"

[font]

normal.family = "CaskaydiaMono Nerd Font"
bold.family = "CaskaydiaMono Nerd Font"
italic.family = "CaskaydiaMono Nerd Font"

size = 15.0

[colors]
primary.background = "#222436"
