cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

brew "ack"
brew "ctags"
brew "docker"
brew "docker-machine"
brew "elixir"
brew "git"
brew "hub"
brew "yarn"
brew "zsh"
brew "neovim"
brew "rbenv"
brew "ruby-build"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "direnv"
brew "redis", restart_service: true
brew "postgresql", restart_service: true
brew "the_silver_searcher"
brew "imagemagick"
brew "cmake"
brew "bat"

cask "tableplus"
cask "sip"
cask "dropbox"
cask "graphql-playground"
cask "google-chrome"
cask "alfred"
cask "dash"
cask "spotify"
cask "slack"
cask "transmission"
cask "vlc"
cask "authy"
cask "bartender"
cask "divvy"
cask "gpg-suite"
cask "aerial"
cask "whatsapp"
cask "textual"
cask "the-unarchiver"
cask "iterm2"
cask "docker"
cask "ngrok"
cask "gifox"
cask "firefox"
cask "spectacle"
cask "hammerspoon"
cask "figma"

mas "todoist", id: 585829637
mas "medis", id: 1063631769
mas "1password", id: 1333542190
