let g:NERDTreeHijackNetrw = 0
let g:NERDTreeMinimalUI = 1
let NERDTreeDirArrows=0
let NERDTreeShowLineNumbers=1
let NERDTreeAutoDeleteBuffer=1
let NERDTreeShowHidden=0
let NERDTreeHighlightCursorline=1
let NERDTreeDirArrowExpandable='|'
let NERDTreeDirArrowCollapsible='-'
